### ISSUE TITLE
Some suggestions/questions

### ISSUE THREAD

**Issue by hexrcs** [DHSTTOS/documents#31]
### Suggestions/Questions

1. Should it be "with Internet access" according to Ankush?

https://github.com/DHSTTOS/documents/blob/7b5a92c3f462b3433a101f00d97848e5d51acc04/Pflichtenheft.tex#L197

2. As a grammar nazi - "Once logged in, a user ..."

https://github.com/DHSTTOS/documents/blob/7b5a92c3f462b3433a101f00d97848e5d51acc04/Pflichtenheft.tex#L244

3. So we still agreed upon having 4+ diagrams? Not max. 4 diagrams or else?

https://github.com/DHSTTOS/documents/blob/7b5a92c3f462b3433a101f00d97848e5d51acc04/Pflichtenheft.tex#L259

https://github.com/DHSTTOS/documents/blob/7b5a92c3f462b3433a101f00d97848e5d51acc04/Pflichtenheft.tex#L307

4. So after all are "should-have"s considered essential or extra stuff?

https://github.com/DHSTTOS/documents/blob/7b5a92c3f462b3433a101f00d97848e5d51acc04/Pflichtenheft.tex#L295

### <sub><sub>*minor*</sub></sub> Suggestions/Questions

1. Why is the extension changed back to UPPERCASE?

https://github.com/DHSTTOS/documents/blob/7b5a92c3f462b3433a101f00d97848e5d51acc04/Pflichtenheft.tex#L892

2. If this script is meant for cleaning up temp files to avoid build failures after updating local repos, we can actually make this into a git hook, perhaps the `post-merge` hook. [Shameless plug](https://www.xiaoru.li/post/git-hooks/).

https://github.com/DHSTTOS/documents/blob/7b5a92c3f462b3433a101f00d97848e5d51acc04/makeclean.sh#L1

**Comment by mgonzalez01** [comment]
yes

**Comment by mgonzalez01** [comment]
1. changed
2.changed, and fixed old change
3. yes
4 technically essential but lower priotity.


suggestions
1. because Klevia's machine does not like it when there's a file that only changes

**Comment by hexrcs** [comment]
> Or maybe we just need a priest.
I thought a computer can't be haunted. Too naive.

> that's an option, he who plugged it, shall write it ;)
:D
