### ISSUE TITLE
Rotating images in LaTeX

### ISSUE THREAD

**Issue by hexrcs** [DHSTTOS/documents#35]
Anyone can help me insert [this](https://github.com/DHSTTOS/documents/blob/e2ec8fb5629c38fb148429b609102f37d702683e/design/UI_tree.png) super wide image into the design document properly? My idea is to rotate it 90 degrees so that it fits the portrait document format. Been trying for a while but none of my methods worked :(

Please refer to this commit: https://github.com/DHSTTOS/documents/commit/e2ec8fb5629c38fb148429b609102f37d702683e.

**Comment by mgonzalez01** [comment]
Fixed.

To rotate an image the format it:

\includegraphics[angle=  90,origin=c ]{filename.fake}

you can combine it with max size to force the image to fit
like this:
\includegraphics[angle=90,origin=c,max size={\textheight}{\textwidth}]{UI_tree.png}

**Comment by hexrcs** [comment]
@mgonzalez01 dude you're a genius
