### ISSUE TITLE
some remarks

### ISSUE THREAD

**Issue by pm8008** [DHSTTOS/documents#36]
1) method getAllTopics:  returns ... kafka *topics

2) getCollectionInRange: is the end value inclusive or exclusive? exclusive would make sense (because then you can first get range[a..b], then range [b..c] and be sure to have no overlap). But either way it needs to be specified here

3) mongoclientmediator
maybe add something fancy like "this class encapsulates the db connection/the specific API of mongodb"

4) line 228: typo: *collection

**Comment by mgonzalez01** [comment]
Thank you for the comments, I'll throw the fixes as well as some diagrams next.

**Comment by mgonzalez01** [comment]
1. yeah, it returns them as a string array,
2. I'll specify it.

3. yeah, you're right, will do
